### ISSUE TITLE
Does not work on Python 3

### ISSUE THREAD

**Issue by mlsimpson** [ilyash/show-struct#6]
Homebrew installed Python defaults to 3, so `/usr/bin/env python` will use Python 3 by default.

```Traceback (most recent call last):
  File "/Users/mattsimpson/show_struct.py", line 62, in <module>
    outline = Outliner().outline(data)
  File "/Users/mattsimpson/show_struct.py", line 38, in outline
    self._outline(data, [])
  File "/Users/mattsimpson/show_struct.py", line 24, in _outline
    for k, v in data.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
```

**Comment by ilyash** [comment]
Hi. Just merged PR that solves the issue.
